### ISSUE TITLE
Suggestion to add a control to show base4

### ISSUE THREAD

**Issue by ppKrauss** [vasturiano/d3-hilbert#1]
Suggestion

To use someting like `parseInt(cell_id,4)` instead of decimal representation. Can be also an *input-radio*, controlling the user decision about decimal or hierarchical.

Rationale

The [*refinement ratio*](https://docs.opengeospatial.org/as/15-104r5/15-104r5.html) of the region-grid indexed by Hilbert and Morton curves is **4**, so the [base 4](https://en.wikipedia.org/wiki/Quaternary_numeral_system) is the natural way to represent Cell ID for humans: the *base4(cell_id)* is also a label of the hierarchy.

**Comment by vasturiano** [comment]
@ppKrauss can you describe more in detail what kind of changes you're imagining in the component's api?

I do agree that base4 is a more natural way to specify hilbert coordinates, but a user can always convert from a base4 string to a number (used in the component methods) using the `parseInt` as you described above. And it's more handy to work with numbers, instead of strings.

**Comment by ppKrauss** [comment]
Hi @vasturiano, I was trying to learn to use `bl.ocks.org`... Now [you can see some clues here](http://bl.ocks.org/ppKrauss/raw/03d10beaaa5ad4663cd63e2195ca7404/), the hierarchical label are on tooltip... But for finesh and produce something useful I need the inverse-functions indicated [in the pull-request](https://github.com/vasturiano/d3-hilbert/pull/3).

**Comment by vasturiano** [comment]
@ppKrauss I've left a comment on your PR. I believe the inverse function you'd like is already possible via `.layout(...)`. 

But thanks for sharing your work. The hexagonal version is really impressive! I would love to see a `d3-hex-space-fill` module with a similar interface as `d3-hilbert` for this. 😃 
May I ask how did you develop the algorithm?

**Comment by ppKrauss** [comment]
Base4 and other cell ID representations, see https://ppkrauss.github.io/Sfc4q/
